#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jul 24 17:06:43 2021

@author: joseph
"""

import arkouda as ak
import sys

def run_test(ak_server, graph_location, num_edges, num_vertices, num_cols, directed):
    ak.connect(connect_url=ak_server)
    graph = ak.graph_file_read(num_edges,num_vertices,num_cols, directed, graph_location)
#testval2 = ak.pdarraycreation.graph_triangle(graph)
    testval2 = ak.pdarraycreation.graph_triangle_edge(graph)
    return testval2

if __name__ == '__main__':
    ak_server = sys.argv[1]
    graph_loc = sys.argv[2]
    num_edges = sys.argv[3]
    num_verts = sys.argv[4]
    num_cols = sys.argv[5]
    directed = sys.argv[6]
    run_test(ak_server, graph_loc, num_edges, num_verts, num_cols, directed)
    
    